theme = "awesome-identity"
baseURL = "https://mloeper.me"
title = "Martin Löper | Cloud Solutions Architect | About Me"

[params.profile]
  portrait = "/imgs/profile_pic.jpg"
  firstname = "Martin"
  lastname = "Löper"
  title = "Cloud Solutions Architect"
  bio = """I'm Martin, a cloud solutions architect working for the start-up company [Nesto](https://nesto-software.de) from Karlsruhe, Germany. 
  
  Over the last couple of years, I realized that life in a growing start-up inevitably had pushed me towards the Dev-Ops boundary. 
  
  Hence, I consider myself **somewhere between Dev and Ops**: Sometimes architecting cloud workloads, sometimes monitoring traffic and scaling activity, sometimes developing a fleet of IoT devices, and most importantly, *embracing lifelong learning*.
  """

[params.contacts]
  github = "MartinLoeper"
  twitter = "martin_loeper"
  linkedin = "martinloeper"
  stackoverflow = "10473469"
  medium = "@martin.loeper"
  email = "martin.loeper@nesto-software.de"
  keybase = "martinloeper"
  gitlab = "MartinLoeper"
  scholar = "mj2VByAAAAAJ"
  acg = "martinloeper"
  credly = "martin-loeper"
  monero = "88SueGxrUvEddjbMCZA5stb7SKFG47Np2ALEhP6Hha6fLTTeewA6PFSgaWto4dMUgk9WmaT5dtVRVSuQEkF6kSZnEgFKroU"
  cv = "https://github.com/MartinLoeper/My-CV/releases/download/latest/cv-martin-loeper.pdf"

[params.meta]
  description = "Martin Löper is a cloud solutions architect working for the start-up company Nesto based in Karlsruhe. This is the official profile."
  keywords = "martin löper, cloud solutions architect, profile, about me, nesto, martin, löper, loeper, john, identity, id, bio, my identity, webpage, website"

[params.footer]
  copyright = "© 2021 Martin Löper. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
